name: CI-CD

on:
  push:
    branches: ['desafios-imersao']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # Repository name with owner. For example, actions/checkout
          repository: # optional, default is ${{ github.repository }}
          # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.

          ref: # optional
          # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT.
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        uses: docker/build-push-action@v5.0.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./kube-news/src
          # Path to the Dockerfile
          file: ./kube-news/src/Dockerfile
          # List of metadata for an image
          labels: |
            org.opencontainers.image.authors=roberto0arruda@hotmail.com
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: |
            roberto0arruda/kube-news:${{ github.run_number }}
            roberto0arruda/kube-news:latest
          # Sets the target stage to build
          target: # optional

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: autenticar na AWS
        run: echo "autenticar AWS"
      - name: configurar o kubeconfig
        run: echo "configurar o kubeconfig"
      - name: aplicar o deploy
        run: echo "executa kubectl apply"
